name: Node.js CI

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    if: github.repository == 'ivgtr/atcoder-ac-archive' # For testing

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test
        run: |
          npm ci
          npm test
